name: She And He Productions
favicon: null
layout_spectrum: 0.13351
typography_spectrum: 0.5495
title: 'She & He Productions'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#bf94b0'
    - '#d6d6d6'
    - '#464646'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.8901892458088696
  rhythmicContrast: 0.3407151286955923
purpose: []
